package com.skinai.app.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.skinai.app.data.model.AnalysisSource
import com.skinai.app.data.model.ScanResult
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.math.roundToInt

/**
 * Generates a simple one-page PDF summary of a scan result, suitable for sharing with a doctor.
 */
object PdfReportGenerator {

    fun generateAndShare(context: Context, result: ScanResult) {
        val file = generate(context, result)
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)

        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(shareIntent, "Share scan report"))
    }

    private fun generate(context: Context, result: ScanResult): File {
        val pageWidth = 595 // A4 at 72dpi
        val pageHeight = 842
        val margin = 40f

        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas

        val titlePaint = Paint().apply { textSize = 20f; isFakeBoldText = true }
        val headerPaint = Paint().apply { textSize = 13f; isFakeBoldText = true }
        val bodyPaint = Paint().apply { textSize = 11f }
        val mutedPaint = Paint().apply { textSize = 10f; color = 0xFF666666.toInt() }

        var y = margin + 10

        canvas.drawText("DermAI — Scan Report", margin, y, titlePaint)
        y += 22

        val dateFormat = SimpleDateFormat("MMMM d, yyyy 'at' h:mm a", Locale.getDefault())
        canvas.drawText("Generated: ${dateFormat.format(Date(result.timestamp))}", margin, y, mutedPaint)
        y += 14
        canvas.drawText(
            "Source: ${if (result.source == AnalysisSource.ONLINE_AI) "Cloud AI Analysis" else "On-Device Analysis"}",
            margin, y, mutedPaint
        )
        y += 24

        canvas.drawText("Scan Category: ${result.category.displayName}", margin, y, headerPaint)
        y += 18
        canvas.drawText(
            "Predicted Condition: ${result.conditionInfo.displayName} (${(result.confidence * 100).roundToInt()}% confidence)",
            margin, y, headerPaint
        )
        y += 18
        canvas.drawText("Urgency Level: ${result.conditionInfo.urgency.label}", margin, y, headerPaint)
        y += 24

        y = drawWrappedSection(canvas, "Overview", result.conditionInfo.overview, margin, y, pageWidth - margin * 2, headerPaint, bodyPaint)
        y = drawBulletSection(canvas, "Common Symptoms", result.conditionInfo.symptoms, margin, y, pageWidth - margin * 2, headerPaint, bodyPaint)
        y = drawBulletSection(canvas, "Warning Signs", result.conditionInfo.warningSigns, margin, y, pageWidth - margin * 2, headerPaint, bodyPaint)
        y = drawBulletSection(canvas, "Precautions", result.conditionInfo.precautions, margin, y, pageWidth - margin * 2, headerPaint, bodyPaint)
        y = drawBulletSection(canvas, "Care Tips", result.conditionInfo.careTips, margin, y, pageWidth - margin * 2, headerPaint, bodyPaint)
        y = drawWrappedSection(canvas, "When to See a Doctor", result.conditionInfo.whenToSeeDoctor, margin, y, pageWidth - margin * 2, headerPaint, bodyPaint)

        y += 10
        val disclaimer = "This report is generated by an AI screening app for general educational purposes only. It is not a medical diagnosis. Please consult a qualified dermatologist for professional evaluation."
        drawWrappedText(canvas, disclaimer, margin, y, pageWidth - margin * 2, mutedPaint)

        document.finishPage(page)

        val outputDir = File(context.cacheDir, "reports").apply { mkdirs() }
        val outFile = File(outputDir, "DermAI_Report_${System.currentTimeMillis()}.pdf")
        FileOutputStream(outFile).use { document.writeTo(it) }
        document.close()

        return outFile
    }

    private fun drawWrappedSection(
        canvas: Canvas, title: String, body: String,
        x: Float, startY: Float, maxWidth: Float, headerPaint: Paint, bodyPaint: Paint
    ): Float {
        if (body.isBlank()) return startY
        var y = startY
        canvas.drawText(title, x, y, headerPaint)
        y += 16
        y = drawWrappedText(canvas, body, x, y, maxWidth, bodyPaint)
        return y + 14
    }

    private fun drawBulletSection(
        canvas: Canvas, title: String, items: List<String>,
        x: Float, startY: Float, maxWidth: Float, headerPaint: Paint, bodyPaint: Paint
    ): Float {
        if (items.isEmpty()) return startY
        var y = startY
        canvas.drawText(title, x, y, headerPaint)
        y += 16
        items.forEach {
            y = drawWrappedText(canvas, "•  $it", x, y, maxWidth, bodyPaint)
            y += 2
        }
        return y + 12
    }

    private fun drawWrappedText(canvas: Canvas, text: String, x: Float, startY: Float, maxWidth: Float, paint: Paint): Float {
        var y = startY
        val words = text.split(" ")
        var line = StringBuilder()
        for (word in words) {
            val testLine = if (line.isEmpty()) word else "$line $word"
            if (paint.measureText(testLine) > maxWidth) {
                canvas.drawText(line.toString(), x, y, paint)
                y += paint.textSize + 4
                line = StringBuilder(word)
            } else {
                line = StringBuilder(testLine)
            }
        }
        if (line.isNotEmpty()) {
            canvas.drawText(line.toString(), x, y, paint)
            y += paint.textSize + 4
        }
        return y
    }
}
